export const MIN_CHROME_VERSION = 148;
export const MAX_SOURCE_BYTES = 32 * 1024 * 1024;
export const MAX_RESULT_BYTES = 32 * 1024 * 1024;
export const MAX_SINGLE_BINARY_MESSAGE_BYTES = 32 * 1024 * 1024;
export const RECONCILIATION_INTERVAL_MS = 5_000;
export const MUTATION_DEBOUNCE_MS = 120;
export const INTERSECTION_ROOT_MARGIN = '1600px 0px';
export const INTERSECTION_THRESHOLD = 0.05;
export const EXTENSION_DOM_PREFIX = 'mte-';
export const RUNTIME_DB_NAME = 'manga-translation-runtime';
export const RUNTIME_DB_VERSION = 1;

export const CACHE_DEFAULT_MAX_BYTES = 256 * 1024 * 1024;
export const CACHE_TTL_MS = 30 * 24 * 60 * 60 * 1000;
export const CACHE_LOW_WATER_RATIO = 0.8;
export const CACHE_TOUCH_COALESCE_MS = 10 * 60 * 1000;
export const CACHE_PRESSURE_HIGH_RATIO = 0.85;
export const CACHE_PRESSURE_TARGET_RATIO = 0.70;
export const MEMORY_SOFT_BUDGET_BYTES = 64 * 1024 * 1024;
export const UNKNOWN_BINARY_RESERVATION_BYTES = 8 * 1024 * 1024;
export const MAX_PREPARED_AHEAD_PER_SESSION = 3;
export const MAX_WORK_CONSUMERS = 256;
export const QUEUE_WAKE_ALARM = 'queue-wake';
export const MIN_DEFERRED_RETRY_MS = 30_000;
export const SCREENSHOT_MIN_START_INTERVAL_MS = 550;

export const ENGINE_POLL_GRACE_MS = 4_000;
export const ENGINE_POLL_INTERVAL_MS = 250;
export const ENGINE_DURABLE_RECHECK_MS = 30_000;
